<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Food;

class SeedNewCategoryFoods extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'food:seed-new-categories';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Seed sample foods for new food categories (chicken, breads-and-cereals, grains-and-cereals, nuts-and-seeds, oils-and-fats, herbs-and-spices, protein-powders)';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $this->info('🌱 Seeding sample foods for new categories...');
        $this->newLine();

        // Sample foods for new categories
        $foods = [
            // Chicken category
            [
                'food_id' => 'chicken_001',
                'name' => 'Grilled Chicken Breast',
                'description' => 'Skinless, boneless chicken breast, grilled',
                'serving_description' => '100g',
                'calories' => 165,
                'fat' => 3.6,
                'saturated_fat' => 1.0,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.8,
                'monounsaturated_fat' => 1.2,
                'cholesterol' => 85,
                'sodium' => 74,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
                'protein' => 31,
                'vitamin_d' => 0.1,
                'calcium' => 15,
                'iron' => 0.9,
                'potassium' => 256,
                'vitamin_a' => 6,
                'vitamin_c' => 0,
                'food_type' => 'chicken',
            ],
            [
                'food_id' => 'chicken_002',
                'name' => 'Chicken Thigh',
                'description' => 'Skinless chicken thigh, cooked',
                'serving_description' => '100g',
                'calories' => 209,
                'fat' => 10.9,
                'saturated_fat' => 2.8,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 2.3,
                'monounsaturated_fat' => 4.2,
                'cholesterol' => 102,
                'sodium' => 95,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
                'protein' => 26,
                'vitamin_d' => 0.1,
                'calcium' => 10,
                'iron' => 1.2,
                'potassium' => 220,
                'vitamin_a' => 8,
                'vitamin_c' => 0,
                'food_type' => 'chicken',
            ],
            [
                'food_id' => 'chicken_003',
                'name' => 'Roasted Chicken',
                'description' => 'Whole roasted chicken, skin removed',
                'serving_description' => '100g',
                'calories' => 190,
                'fat' => 7.4,
                'saturated_fat' => 2.0,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 1.6,
                'monounsaturated_fat' => 2.8,
                'cholesterol' => 88,
                'sodium' => 87,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
                'protein' => 29,
                'vitamin_d' => 0.1,
                'calcium' => 12,
                'iron' => 1.0,
                'potassium' => 240,
                'vitamin_a' => 7,
                'vitamin_c' => 0,
                'food_type' => 'chicken',
            ],

            // Breads & Cereals category
            [
                'food_id' => 'bread_001',
                'name' => 'Whole Wheat Bread',
                'description' => '100% whole wheat bread',
                'serving_description' => '1 slice (28g)',
                'calories' => 81,
                'fat' => 1.1,
                'saturated_fat' => 0.2,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.5,
                'monounsaturated_fat' => 0.2,
                'cholesterol' => 0,
                'sodium' => 170,
                'carbohydrate' => 13.8,
                'fiber' => 1.9,
                'sugar' => 1.4,
                'protein' => 4.0,
                'vitamin_d' => 0,
                'calcium' => 40,
                'iron' => 0.9,
                'potassium' => 81,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'breads-and-cereals',
            ],
            [
                'food_id' => 'bread_002',
                'name' => 'White Bread',
                'description' => 'Classic white bread',
                'serving_description' => '1 slice (25g)',
                'calories' => 66,
                'fat' => 0.8,
                'saturated_fat' => 0.2,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.3,
                'monounsaturated_fat' => 0.2,
                'cholesterol' => 0,
                'sodium' => 149,
                'carbohydrate' => 12.7,
                'fiber' => 0.6,
                'sugar' => 1.4,
                'protein' => 2.0,
                'vitamin_d' => 0,
                'calcium' => 33,
                'iron' => 0.8,
                'potassium' => 28,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'breads-and-cereals',
            ],
            [
                'food_id' => 'cereal_001',
                'name' => 'Oatmeal',
                'description' => 'Cooked oatmeal, plain',
                'serving_description' => '1 cup (234g)',
                'calories' => 166,
                'fat' => 3.6,
                'saturated_fat' => 0.7,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 1.3,
                'monounsaturated_fat' => 1.1,
                'cholesterol' => 0,
                'sodium' => 9,
                'carbohydrate' => 28.1,
                'fiber' => 4.0,
                'sugar' => 0.6,
                'protein' => 5.9,
                'vitamin_d' => 0,
                'calcium' => 21,
                'iron' => 1.8,
                'potassium' => 164,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'breads-and-cereals',
            ],

            // Grains & Cereals category
            [
                'food_id' => 'grain_001',
                'name' => 'Quinoa',
                'description' => 'Cooked quinoa',
                'serving_description' => '1 cup (185g)',
                'calories' => 222,
                'fat' => 3.6,
                'saturated_fat' => 0.4,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 1.6,
                'monounsaturated_fat' => 0.9,
                'cholesterol' => 0,
                'sodium' => 13,
                'carbohydrate' => 39.4,
                'fiber' => 5.2,
                'sugar' => 1.6,
                'protein' => 8.1,
                'vitamin_d' => 0,
                'calcium' => 31,
                'iron' => 2.8,
                'potassium' => 318,
                'vitamin_a' => 5,
                'vitamin_c' => 0,
                'food_type' => 'grains-and-cereals',
            ],
            [
                'food_id' => 'grain_002',
                'name' => 'Brown Rice',
                'description' => 'Cooked brown rice',
                'serving_description' => '1 cup (202g)',
                'calories' => 248,
                'fat' => 2.0,
                'saturated_fat' => 0.4,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.6,
                'monounsaturated_fat' => 0.6,
                'cholesterol' => 0,
                'sodium' => 10,
                'carbohydrate' => 51.7,
                'fiber' => 3.2,
                'sugar' => 0.4,
                'protein' => 5.5,
                'vitamin_d' => 0,
                'calcium' => 20,
                'iron' => 0.8,
                'potassium' => 84,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'grains-and-cereals',
            ],
            [
                'food_id' => 'grain_003',
                'name' => 'Barley',
                'description' => 'Cooked pearl barley',
                'serving_description' => '1 cup (157g)',
                'calories' => 193,
                'fat' => 0.7,
                'saturated_fat' => 0.1,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.3,
                'monounsaturated_fat' => 0.1,
                'cholesterol' => 0,
                'sodium' => 5,
                'carbohydrate' => 44.3,
                'fiber' => 6.0,
                'sugar' => 0.4,
                'protein' => 3.6,
                'vitamin_d' => 0,
                'calcium' => 17,
                'iron' => 1.3,
                'potassium' => 146,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'grains-and-cereals',
            ],

            // Nuts & Seeds category
            [
                'food_id' => 'nut_001',
                'name' => 'Almonds',
                'description' => 'Raw almonds',
                'serving_description' => '1 oz (28g)',
                'calories' => 164,
                'fat' => 14.2,
                'saturated_fat' => 1.1,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 3.5,
                'monounsaturated_fat' => 9.0,
                'cholesterol' => 0,
                'sodium' => 1,
                'carbohydrate' => 6.1,
                'fiber' => 3.5,
                'sugar' => 1.2,
                'protein' => 6.0,
                'vitamin_d' => 0,
                'calcium' => 76,
                'iron' => 1.1,
                'potassium' => 208,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'nuts-and-seeds',
            ],
            [
                'food_id' => 'nut_002',
                'name' => 'Walnuts',
                'description' => 'Raw walnuts',
                'serving_description' => '1 oz (28g)',
                'calories' => 185,
                'fat' => 18.5,
                'saturated_fat' => 1.7,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 13.4,
                'monounsaturated_fat' => 2.5,
                'cholesterol' => 0,
                'sodium' => 1,
                'carbohydrate' => 3.9,
                'fiber' => 1.9,
                'sugar' => 0.7,
                'protein' => 4.3,
                'vitamin_d' => 0,
                'calcium' => 28,
                'iron' => 0.8,
                'potassium' => 125,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'nuts-and-seeds',
            ],
            [
                'food_id' => 'seed_001',
                'name' => 'Chia Seeds',
                'description' => 'Dried chia seeds',
                'serving_description' => '1 oz (28g)',
                'calories' => 138,
                'fat' => 8.7,
                'saturated_fat' => 0.8,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 6.5,
                'monounsaturated_fat' => 0.6,
                'cholesterol' => 0,
                'sodium' => 5,
                'carbohydrate' => 12.3,
                'fiber' => 10.6,
                'sugar' => 0,
                'protein' => 4.7,
                'vitamin_d' => 0,
                'calcium' => 179,
                'iron' => 2.2,
                'potassium' => 115,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'nuts-and-seeds',
            ],

            // Oils & Fats category
            [
                'food_id' => 'oil_001',
                'name' => 'Olive Oil',
                'description' => 'Extra virgin olive oil',
                'serving_description' => '1 tbsp (14g)',
                'calories' => 119,
                'fat' => 13.5,
                'saturated_fat' => 1.9,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 1.4,
                'monounsaturated_fat' => 10.0,
                'cholesterol' => 0,
                'sodium' => 0,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
                'protein' => 0,
                'vitamin_d' => 0,
                'calcium' => 0,
                'iron' => 0.1,
                'potassium' => 0,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'oils-and-fats',
            ],
            [
                'food_id' => 'oil_002',
                'name' => 'Coconut Oil',
                'description' => 'Virgin coconut oil',
                'serving_description' => '1 tbsp (14g)',
                'calories' => 121,
                'fat' => 13.5,
                'saturated_fat' => 11.7,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.2,
                'monounsaturated_fat' => 0.9,
                'cholesterol' => 0,
                'sodium' => 0,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
                'protein' => 0,
                'vitamin_d' => 0,
                'calcium' => 0,
                'iron' => 0,
                'potassium' => 0,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'oils-and-fats',
            ],
            [
                'food_id' => 'oil_003',
                'name' => 'Avocado Oil',
                'description' => 'Pure avocado oil',
                'serving_description' => '1 tbsp (14g)',
                'calories' => 124,
                'fat' => 14.0,
                'saturated_fat' => 1.6,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 1.8,
                'monounsaturated_fat' => 10.2,
                'cholesterol' => 0,
                'sodium' => 0,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
                'protein' => 0,
                'vitamin_d' => 0,
                'calcium' => 0,
                'iron' => 0,
                'potassium' => 0,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'oils-and-fats',
            ],

            // Herbs & Spices category
            [
                'food_id' => 'herb_001',
                'name' => 'Basil',
                'description' => 'Fresh basil leaves',
                'serving_description' => '1 tbsp (2.5g)',
                'calories' => 1,
                'fat' => 0,
                'saturated_fat' => 0,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'cholesterol' => 0,
                'sodium' => 0,
                'carbohydrate' => 0.2,
                'fiber' => 0.1,
                'sugar' => 0,
                'protein' => 0.1,
                'vitamin_d' => 0,
                'calcium' => 9,
                'iron' => 0.2,
                'potassium' => 15,
                'vitamin_a' => 264,
                'vitamin_c' => 1.0,
                'food_type' => 'herbs-and-spices',
            ],
            [
                'food_id' => 'spice_001',
                'name' => 'Turmeric',
                'description' => 'Ground turmeric',
                'serving_description' => '1 tsp (2.1g)',
                'calories' => 7,
                'fat' => 0.2,
                'saturated_fat' => 0.1,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.1,
                'monounsaturated_fat' => 0,
                'cholesterol' => 0,
                'sodium' => 1,
                'carbohydrate' => 1.4,
                'fiber' => 0.5,
                'sugar' => 0.1,
                'protein' => 0.2,
                'vitamin_d' => 0,
                'calcium' => 5,
                'iron' => 1.7,
                'potassium' => 48,
                'vitamin_a' => 0,
                'vitamin_c' => 0.3,
                'food_type' => 'herbs-and-spices',
            ],
            [
                'food_id' => 'spice_002',
                'name' => 'Cumin',
                'description' => 'Ground cumin',
                'serving_description' => '1 tsp (2.1g)',
                'calories' => 8,
                'fat' => 0.5,
                'saturated_fat' => 0.1,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.1,
                'monounsaturated_fat' => 0.2,
                'cholesterol' => 0,
                'sodium' => 4,
                'carbohydrate' => 0.9,
                'fiber' => 0.2,
                'sugar' => 0.1,
                'protein' => 0.4,
                'vitamin_d' => 0,
                'calcium' => 20,
                'iron' => 1.4,
                'potassium' => 36,
                'vitamin_a' => 26,
                'vitamin_c' => 0.2,
                'food_type' => 'herbs-and-spices',
            ],

            // Protein Powders category
            [
                'food_id' => 'protein_001',
                'name' => 'Whey Protein Powder',
                'description' => 'Whey protein isolate',
                'serving_description' => '1 scoop (30g)',
                'calories' => 110,
                'fat' => 0.5,
                'saturated_fat' => 0.3,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0,
                'monounsaturated_fat' => 0.1,
                'cholesterol' => 5,
                'sodium' => 50,
                'carbohydrate' => 2.0,
                'fiber' => 0,
                'sugar' => 1.0,
                'protein' => 25.0,
                'vitamin_d' => 0,
                'calcium' => 100,
                'iron' => 0.5,
                'potassium' => 150,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'protein-powders',
            ],
            [
                'food_id' => 'protein_002',
                'name' => 'Plant Protein Powder',
                'description' => 'Pea and rice protein blend',
                'serving_description' => '1 scoop (30g)',
                'calories' => 120,
                'fat' => 2.0,
                'saturated_fat' => 0.5,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.8,
                'monounsaturated_fat' => 0.5,
                'cholesterol' => 0,
                'sodium' => 200,
                'carbohydrate' => 3.0,
                'fiber' => 1.0,
                'sugar' => 1.0,
                'protein' => 22.0,
                'vitamin_d' => 0,
                'calcium' => 150,
                'iron' => 3.0,
                'potassium' => 200,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'protein-powders',
            ],
            [
                'food_id' => 'protein_003',
                'name' => 'Casein Protein Powder',
                'description' => 'Micellar casein protein',
                'serving_description' => '1 scoop (33g)',
                'calories' => 120,
                'fat' => 1.0,
                'saturated_fat' => 0.5,
                'trans_fat' => 0,
                'polyunsaturated_fat' => 0.2,
                'monounsaturated_fat' => 0.2,
                'cholesterol' => 10,
                'sodium' => 60,
                'carbohydrate' => 3.0,
                'fiber' => 0,
                'sugar' => 2.0,
                'protein' => 24.0,
                'vitamin_d' => 0,
                'calcium' => 200,
                'iron' => 0.5,
                'potassium' => 100,
                'vitamin_a' => 0,
                'vitamin_c' => 0,
                'food_type' => 'protein-powders',
            ],
        ];

        $inserted = 0;
        $skipped = 0;

        // Insert foods into database
        foreach ($foods as $food) {
            // Check if food already exists
            $existing = Food::where('food_id', $food['food_id'])->first();
            if (!$existing) {
                Food::create($food);
                $inserted++;
                $this->line("✅ Added: {$food['name']} ({$food['food_type']})");
            } else {
                $skipped++;
                $this->line("⏭️  Skipped: {$food['name']} (already exists)");
            }
        }

        $this->newLine();
        $this->info("✨ Seeding complete! Added {$inserted} foods, skipped {$skipped} existing foods.");

        return 0;
    }
}
